### ISSUE TITLE
Only characters of the last categories are used to complete the password

### ISSUE THREAD

**Issue by LudoPL** [jgweir/randstring#1]
I discovered the issue running the following code:
```
rs := randstring.New(12)
rs.SetSpecialChars("-")
password, _ := rs.Build()
```
which was generating password like `--J----h--1-` that contains only one uppercase, one lowercase and one digit.
The issue comes from those lines :
```
all = append([]rune(r.SpecialChars))
```
This line doesn't add the `r.SpecialChars` characters to the current `all` slice, it replaces the content of the `all` slice with the `r.SpecialChars`.

**Comment by jgweir** [comment]
Fixed. Thanks for the feedback
